name: Cancel event when issue was closed before it took place

on:
  issues:
    types:
      - closed

jobs:

  cancel_event:
    env:
      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
      CALENDAR_SERVICE_ACCOUNT: ${{ secrets.CALENDAR_SERVICE_ACCOUNT }}
    name: Remove event from calendar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: '**/package-lock.json'
      - name: Install deps
        run: npm install
        working-directory: ./.github/workflows/create-event-helpers
      - name: Remove Google Calendar entry
        uses: actions/github-script@v4
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_CLOSED_AT: ${{ github.event.issue.closed_at }}
        with:
          script: |
            const { deleteEvent } = require('./.github/workflows/create-event-helpers/calendar/index.js');
            deleteEvent(process.env.ISSUE_NUMBER, process.env.ISSUE_CLOSED_AT);