name: Schedule Ad Hoc Meeting

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'Info about meeting time in UTC time zone in "HH:MM"(MM can be 00 or 30), like: 08:30 or 16:00. No PM or AM versions.'
        required: true
      date:
        description: 'Date in a form like: 2022-04-05 where 04 is a month and 05 is a day number.'
        required: true
      name:
        description: 'Provide short title for the meeting.'
        required: true
      desc:
        description: 'Provide a description that explains meeting purpose'
        required: true
      meeting_banner: 
        description: 'Meeting banner(image) URL'
        required: false

jobs:

  setup-ad-hoc:
    uses: ./.github/workflows/create-event-workflow-reusable.yml
    with:
      time: ${{ github.event.inputs.time }}
      date: ${{ github.event.inputs.date }}
      meeting_name: ${{ github.event.inputs.name }}
      meeting_desc: ${{ github.event.inputs.desc }}
      meeting_banner: ${{ github.event.inputs.meeting_banner }}
      host: lpgornicki@gmail.com
      alternative_host: "muibudeenaishat@gmail.com,devlopergene@gmail.com,sibanda.thulie@gmail.com,oluwabamikemi@gmail.com,prince.rajpoot.20@gmail.com"
      issue_template_path: .github/workflows/create-event-helpers/issues_templates/ad-hoc.md
      create_zoom: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ZOOM_ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
      ZOOM_TOKEN: ${{ secrets.ZOOM_TOKEN }}
      STREAM_URL: ${{ secrets.STREAM_URL }}
      STREAM_KEY: ${{ secrets.STREAM_KEY }}
      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
      CALENDAR_SERVICE_ACCOUNT: ${{ secrets.CALENDAR_SERVICE_ACCOUNT }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }} 
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }} 
      TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
