name: Schedule X Template Workflow

on:
  workflow_call:
    inputs:
      time:
        description: 'Info about meeting time in UTC time zone in "HH:MM"(MM can be 00 or 30), like: 08:30 or 16:00. No PM or AM versions.'
        required: true
        type: string
      date:
        description: 'Date in a form like: 2022-04-05 where 04 is a month and 05 is a day number.'
        required: true
        type: string
      meeting_name:
        description: 'Name of the meeting.'
        required: true
        type: string
      meeting_name_suffix:
        description: 'Optional additional description added at the end of meeting title to indicate purpose of given meeting.'
        type: string
        required: false
      meeting_desc:
        description: 'Description of the purpose of the meeting.'
        required: true
        type: string
      host:
        description: 'Email address of the host of the meeting.'
        required: true
        type: string
      guest:
        description: 'Name of extra guest for the meeting.'
        required: false
        type: string
      alternative_host:
        description: 'Email address of alternative hosts of the meeting.'
        required: false
        type: string
      issue_template_path:
        description: 'Path to the issue template used to create meeting GH issue.'
        required: true
        type: string
      create_zoom:
        description: 'Boolean information if meeting.'
        required: true
        type: boolean
      meeting_banner:
        description: 'Meeting banner(image) URL'
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true
      ZOOM_ACCOUNT_ID:
        required: true
      ZOOM_TOKEN:
        required: true
      STREAM_URL:
        required: true
      STREAM_KEY:
        required: true
      CALENDAR_ID:
        required: true
      CALENDAR_SERVICE_ACCOUNT:
        required: true
      TWITTER_CONSUMER_KEY:
        required: true
      TWITTER_CONSUMER_SECRET:
        required: true
      TWITTER_ACCESS_TOKEN_KEY:
        required: true
      TWITTER_ACCESS_TOKEN_SECRET:
        required: true

jobs:
  setup-meeting:
    env:
      ZOOM_ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
      ZOOM_TOKEN: ${{ secrets.ZOOM_TOKEN }}
      STREAM_URL: ${{ secrets.STREAM_URL }}
      STREAM_KEY: ${{ secrets.STREAM_KEY }}
      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
      CALENDAR_SERVICE_ACCOUNT: ${{ secrets.CALENDAR_SERVICE_ACCOUNT }}
    name: Setup meeting
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        uses: actions/github-script@v6
        with:
          script: |
            const time = '${{inputs.time}}'
            const [HH, MM] = time.split(':')
            if(Number(HH) > 23 || Number(HH) < 0 || !(Number(MM) === 0 || Number(MM) === 30)){
              core.setFailed(`${time} is an invalid input. Time should be in UTC time zone in "HH:MM"(MM can be 00 or 30), like: 08:30 or 16:00. No PM or AM versions.`);
            }
            // Validate if the event is in the future
            const eventDate = new Date('${{ inputs.date }}T${{ inputs.time }}:00Z');
            const currentDate = new Date();
            if (eventDate <= currentDate) {
              let errorMessage = `The event cannot be scheduled in the past. You attempted to schedule the event on ${eventDate.toLocaleString()}, but the current date and time is ${currentDate.toLocaleString()}. Please specify a future date and time for the event.`;
              core.setFailed(errorMessage);
            }
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install deps
        run: npm install
        working-directory: ./.github/workflows/create-event-helpers
      - if: inputs.create_zoom == true
        name: Create zoom meeting
        uses: actions/github-script@v6
        id: zoom
        env:
          MEETING_NAME: ${{ inputs.meeting_name }}
        with:
          script: |
            const setupZoom = require('./.github/workflows/create-event-helpers/zoom/index.js');
            setupZoom('${{ inputs.date }}', '${{ inputs.time }}', '${{ inputs.host }}', '${{ inputs.alternative_host }}');
      - name: Create issue with meeting details
        uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          FULL_DATE: ${{ inputs.date }}T${{ inputs.time }}:00Z
          DATE_ONLY: ${{ inputs.date }}
          ZOOM_LINK: ${{ steps.zoom.outputs.meetingUrl }}
          MEETING_NAME: ${{ inputs.meeting_name }}
          MEETING_NAME_SUFFIX: ${{ inputs.meeting_name_suffix }}
          MEETING_DESC: ${{ inputs.meeting_desc }}
          MEETING_BANNER: ${{ inputs.meeting_banner }}
          GUEST: ${{ inputs.guest }}
        with:
          filename: ${{ inputs.issue_template_path }}
      - name: Create Google Calendar entry
        uses: actions/github-script@v4
        env:
          MEETING_NAME: ${{ inputs.meeting_name }}
          MEETING_NAME_SUFFIX: ${{ inputs.meeting_name_suffix }}
          MEETING_DESC: ${{ inputs.meeting_desc }}
          MEETING_BANNER: ${{ inputs.meeting_banner }}
          GUEST: ${{ inputs.guest }}
        with:
          script: |
            const { addEvent } = require('./.github/workflows/create-event-helpers/calendar/index.js');
            addEvent('${{ steps.zoom.outputs.meetingUrl }}', '${{ inputs.date }}', '${{ inputs.time }}', '${{ steps.create-issue.outputs.number }}');
      - name: Publish information about meeting to Twitter
        uses: m1ner79/Github-Twittction@v1.0.1
        with:
          twitter_status: "New meeting scheduled ğŸ’ª\n\nName: ${{ inputs.meeting_name }}\n\nCheck what is it about and how to connect ğŸ‘‡ğŸ¼ https://github.com/asyncapi/community/issues/${{ steps.create-issue.outputs.number }}"
          twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
