name: Welcome New Contributor

on:
  pull_request:
    types: [closed]
    paths: 
      - 'MAINTAINERS.yaml'

jobs:
  welcome:
    if: github.event.pull_request.merged 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout main branch 
        uses: actions/checkout@v3
        with:
          ref: master
          path: community-main
      - name: List of directory
        run: ls -la
      - name: Checkout one commit before last one
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: master
          path: community
      - name: List of directory 
        run: ls -la
      - run: cd community && git checkout HEAD^
      - name: Install dependencies
        run: npm install js-yaml@4.1.0
      - name: Compare files
        id: compare-files
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const yaml = require('js-yaml');

            const main_file = yaml.load(fs.readFileSync('./community-main/MAINTAINERS.yaml', 'utf8'));
            const main_file = yaml.load(fs.readFileSync('./community/MAINTAINERS.yaml', 'utf8'));

            const removed = pr_file.filter(
              (newObj) => !main_file.some((oldObj) => oldObj.github === newObj.github)
            );
            const added = main_file.filter(
              (oldObj) => !pr_file.some((newObj) => newObj.github === oldObj.github)
            );

            if(added.length > 0) {
              core.info(`Added Contributors:\n${yaml.dump(added)}`);
              core.setOutput("newContributors", added.map((obj) => obj.github).join(","));
            }
             if (removed.length > 0) {
              core.setOutput("removedMaintainers", removed.map((obj) => obj.github).join(","));
            }

            core.info('Maintainers in main branch:\n' + yaml.dump(main_file));
            core.info('Location of Maintainers in main branch:');
            core.info(fs.realpathSync('./community-main/MAINTAINERS.yaml'));
            core.info('Maintainers in PR branch:\n' + yaml.dump(pr_file));
            core.info('Location of Maintainers in PR branch:');
            core.info(fs.realpathSync('./community/MAINTAINERS.yaml'));

      - name: Set newMaintainers as environment variable
        run: echo "newMaintainers=${{ steps.compare-files.outputs.newMaintainers }}" >> $GITHUB_ENV
      - name: Debug newMaintainers output
        run: |
          echo "newMaintainers = $newMaintainers"
    outputs:
      newMaintainers: ${{ steps.compare-files.outputs.newMaintainers }}
      removedMaintainers: ${{ steps.compare-files.outputs.removedMaintainers }}

  add_maintainer:
    needs: welcome
    if: needs.welcome.outputs.newMaintainers != ''
    runs-on: ubuntu-latest
    steps:
      - name: Invite new maintainers to the organization
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra MAINTAINERS <<< "${{ needs.welcome.outputs.newMaintainers }}"
          for MAINTAINER in "${MAINTAINERS[@]}"; do
            gh api -X PUT /orgs/asyncapi/memberships/$MAINTAINER -H "Authorization: token $GH_TOKEN"
          done

      - name: Add new maintainers to the team
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra MAINTAINERS <<< "${{ needs.welcome.outputs.newMaintainers }}"
          for MAINTAINER in "${MAINTAINERS[@]}"; do
            gh api orgs/asyncapi/teams/maintainers/memberships/$MAINTAINER -H "Authorization: token $GH_TOKEN" -X PUT
          done

  display_message:
    needs: add_maintainer
    if: needs.welcome.outputs.newMaintainers != ''
    runs-on: ubuntu-latest
    steps:
      - name: Display welcome message
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const newMaintainers = process.env.newMaintainers.split(",");
            const welcomeMessage = newMaintainers.map((maintainer) => `@${maintainer.trim().replace(/^@/, '')} I have invited you to join the AsyncAPI organization and you will soon be added to the team that lists all Maintainers.
            We use this team to mention in different discussions in different places in GitHub where Maintainer's opinion is needed or even voting on some topic. Once Maintainers are mentioned:
            - You get GitHub notification
            - We also drop notification in our slack in #95_bot-maintainers-mentioned channel
            - We drop an email to people that subscribed to Maintainer news here https://www.asyncapi.com/community/maintainers
            Pick the channel for notifications that you prefer. Welcome aboard! We are excited to have you as part of the team.`).join("\n");
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            return github.rest.issues.createComment({ owner, repo, issue_number, body: welcomeMessage });
      - if: failure() # Only, on failure, send a message on the 94_bot-failing-ci slack channel
        name: Report workflow run status to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_CI_FAIL_NOTIFY}}
          SLACK_TITLE: ðŸš¨ Welcome new contributor action failed ðŸš¨
          SLACK_MESSAGE: Failed to post a message to new Maintainer
          MSG_MINIMAL: true

  remove_maintainer:
    needs: welcome
    if: needs.welcome.outputs.removedMaintainers != ''
    runs-on: ubuntu-latest
    steps:
      - name: Remove maintainers from the organization
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra MAINTAINERS <<< "${{ needs.welcome.outputs.removedMaintainers }}"
          for MAINTAINER in "${MAINTAINERS[@]}"; do
            gh api -X DELETE /orgs/asyncapi/memberships/$MAINTAINER -H "Authorization: token $GH_TOKEN"
          done

      - name: Remove maintainers from the team
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra MAINTAINERS <<< "${{ needs.welcome.outputs.removedMaintainers }}"
          for MAINTAINER in "${MAINTAINERS[@]}"; do
            gh api orgs/asyncapi/teams/maintainers/memberships/$MAINTAINER -H "Authorization: token $GH_TOKEN" -X DELETE
          done   