name: Welcome New Contributor
on:
  pull_request:
    types: [opened]
    paths: 
      - 'TSC_MEMBERS.json'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout main branch 
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Save file from main branch 
        run: cp TSC_MEMBERS.json $HOME
      - name: Checkout other branch
        uses: actions/checkout@v2
        with: 
          ref: ${{github.event.inputs.branch}}
      - name: Compare files
        id: compare-files
        run: |
          # Read in the contents of both files
          main_file=$(cat $HOME/TSC_MEMBERS.json)
          other_file=$(cat TSC_MEMBERS.json)
          if [[ "$main_file" != "$other_file" ]]; then
            echo "::set-output name=modified::true"
          fi
      - name: Display welcome message
        if: steps.compare-files.outputs.modified == 'true'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const welcomeMessage = `Welcome to AsyncAPI. Thanks a lot for creating your first pull request. Please check out our [contributors guide](https://github.com/asyncapi/community/blob/master/CONTRIBUTING.md) useful for opening a pull request.<br />Keep in mind there are also other channels you can use to interact with AsyncAPI community.`;
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            return github.issues.createComment({ owner, repo, issue_number, body: welcomeMessage });