on:
  schedule:
    # Schedule when tweet should go out
    # At 09:00 on the first day of the month, every month.
    # https://crontab.guru/#0_9_1_*_*
    - cron: "0 9 1 * *"

name: Create tweet about ideas # provide custom name for reoccuring workflow that will help identify what is it about
jobs:
  create-ideas-tweet: # provide clear identifier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node to execute script
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Create another copy of the tweet
        run: TWEET_FILENAME=discuss-ideas.tweet node ./.github/scripts/createTweetFile.js # provide a file name of the reoccuring tweet that you created
      - name: Create Pull Request with new tweet
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'chore(tweet): reoccuring tweet about discussion tools ideas in our discussions forum' # put some sort description
          committer: asyncapi-bot <info@asyncapi.io>
          author: asyncapi-bot <info@asyncapi.io>
          title: 'chore(tweet): reoccuring tweet about discussion tools ideas in our discussions forum' # put some sort description
          body: 'This is a tweet that we want to share regularly to make sure all AsyncAPI folowers know about discussions forum' # put some longer description
          branch: 'tweet/${{github.job}}'