name: Validate Maintainers
on:
  pull_request:
    paths:
      - "Maintainers.yml"
    types:
      - opened
      - reopened
      - edited

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check last committer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ "$(git log -1 --pretty=format:'%an' ${{ github.event.inputs.path }})" != "asyncapi-bot" ]; then
            echo "Error: Changes to ${{ github.event.inputs.path }} file must be made by the bot."

            # Add a comment to the PR explaining why it was blocked
            curl -s -X POST -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ env.REPO }}/issues/${{ env.PR_NUMBER }}/comments \
              -d '{"body":"This PR was blocked because changes to Maintainers.yml should only be made by asyncapi-bot. Please revert your changes."}'

            # Request changes to the PR to prevent merge
            curl -X POST -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ env.REPO }}/pulls/${{ env.PR_NUMBER }}/reviews \
              -d '{"event": "REQUEST_CHANGES", "body": "Changes to Maintainers.yml should only be made by asyncapi-bot."}'

            exit 1
          fi
